apiVersion: apps/v1 
kind: Deployment
metadata:
  name: django
  namespace: default
  labels:
    app: django
spec:
  selector: 
    matchLabels:
      app: django
  replicas: 1
  template:
    metadata:
      labels:
        app: django
    spec:  
      containers:
        - name: django 
          image: mrbghndevops/django:metrics
          ports:
            - name: http
              containerPort: 8000
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 250m  
              memory: 250Mi

---

apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: default
  labels:
    app: django
spec:
  selector:
    app: django
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  type: LoadBalancer
