apiVersion: apps/v1 
kind: Deployment
metadata:
  name: django
  labels:
    app.kubernetes.io/name: django
  name: django
spec:
  selector: 
    matchLabels:
      app.kubernetes.io/name: django
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: django
    spec:  
      containers:
        - name: django 
          image: mrbghndevops/django:metrics
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 250m  
              memory: 250Mi

---

apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app.kubernetes.io/name: django
spec:
  selector:
    app.kubernetes.io/name: django
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer