version: '3'
services:
  django-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    command: python3 manage.py runserver 0.0.0.0:8000

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django-app
