apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: django-monitor
  namespace: default
  labels: 
    release: prometheus
spec:
  selector:
    matchLabels:
      app: django
  endpoints:
    - port: web
      interval: 15s
      path: /metrics
      scheme: http
  namespaceSelector:
    matchNames:
      - default
